NUMPY

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

NUMPY OPERATIONS

In [6]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.ndim

2

In [7]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.itemsize

4

In [8]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.dtype

dtype('int32')

In [9]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.size

9

In [10]:
a.shape

(3, 3)

In [11]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [16]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a[0]

array([1, 2, 3])

In [18]:
a[0,2]

3

In [19]:
a[0:,2]

array([3, 6, 9])

In [20]:
a[0:2,1]

array([2, 5])

In [22]:
a=np.linspace(1,3,10)
a

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [23]:
a.min()

1.0

In [24]:
a.max()

3.0

In [25]:
a.sum()

20.0

In [27]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
a.sum(axis=0)

array([12, 15, 18])

In [29]:
a.sum(axis=1)

array([ 6, 15, 24])

In [30]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [32]:
np.std(a)

2.581988897471611

In [35]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([[7,8,3],[2,0,5],[8,3,6]])
x+y

array([[ 8, 10,  6],
       [ 6,  5, 11],
       [15, 11, 15]])

In [36]:
x-y

array([[-6, -6,  0],
       [ 2,  5,  1],
       [-1,  5,  3]])

In [37]:
x/y

c:\users\ayush mishra\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.14285714, 0.25      , 1.        ],
       [2.        ,        inf, 1.2       ],
       [0.875     , 2.66666667, 1.5       ]])

In [38]:
x**y

array([[      1,     256,      27],
       [     16,       1,    7776],
       [5764801,     512,  531441]], dtype=int32)

In [39]:
x*y

array([[ 7, 16,  9],
       [ 8,  0, 30],
       [56, 24, 54]])

#VERTICAL STACKING

In [40]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([[7,8,3],[2,0,5],[8,3,6]])
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 3],
       [2, 0, 5],
       [8, 3, 6]])

PANDAS

In [44]:
import pandas as pd
import numpy as np

In [45]:
lst1=['a','b','c']
lst2=[1,2,3]
arr=np.array(lst2)
pd.Series(lst1)

0    a
1    b
2    c
dtype: object

In [46]:
pd.Series(lst1,index=lst2)

1    a
2    b
3    c
dtype: object

In [47]:
pd.Series(arr,index=lst1)

a    1
b    2
c    3
dtype: int32

OPERATIONS


In [48]:
list=['a','b','c']
list

['a', 'b', 'c']

In [50]:
list_var=list*2
list_var

['a', 'b', 'c', 'a', 'b', 'c']

In [51]:
ser=pd.Series(list)
ser

0    a
1    b
2    c
dtype: object

In [52]:
ser_var=ser*2
ser_var

0    aa
1    bb
2    cc
dtype: object

In [53]:
s1=pd.Series([1,2],['maths','english'])
s1

maths      1
english    2
dtype: int64

In [55]:
s2=pd.Series([1,2],['maths','hindi'])
s2

maths    1
hindi    2
dtype: int64

In [56]:
s1+s2

english    NaN
hindi      NaN
maths      2.0
dtype: float64

DATAFRAMES

In [59]:
import numpy as np
import pandas as pd
from numpy.random import randn
np.random.seed(101)
df=pd.DataFrame(randn(3,3),['A','B','C'],['D','E','F'])
df

D         E         F
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318
C -0.848077  0.605965 -2.018168

In [60]:
df['D']

A    2.706850
B    0.503826
C   -0.848077
Name: D, dtype: float64

In [61]:
df['E']

A    0.628133
B    0.651118
C    0.605965
Name: E, dtype: float64

In [62]:
type(df['D'])

pandas.core.series.Series

In [63]:
type(df)

pandas.core.frame.DataFrame

In [64]:
df.head(2)

D         E         F
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318

In [65]:
df.tail(1)

D         E         F
C -0.848077  0.605965 -2.018168

In [66]:
df.isnull().any()


D    False
E    False
F    False
dtype: bool

In [67]:
df.drop('C')

D         E         F
A  2.706850  0.628133  0.907969
B  0.503826  0.651118 -0.319318